seed: 3407

# Directory settings
root_dir: "/home/suguilin/MMFS/"
abs_dir: "."
dataset_name: "FMB"
dataset_path: "datasets/FMB"

# Dataset settings
rgb_root_folder: "datasets/FMB/Visible"
rgb_format: ".png"
x_root_folder: "datasets/FMB/Infrared"
x_format: ".png"
text_root_folder: "datasets/FMB/Text_Bert" # "datasets/MFNet/Text"
text_format: ".npy" # ".txt"
guide_root_folder: "datasets/FMB/Guide"
guide_format: ".png"
label_root_folder: "datasets/FMB/Label"
label_format: ".png"
gt_transform: false

# Classes and labels
num_classes: 15
class_names: 
  [
    'background', 
    'Road', 
    'Sidewalk', 
    'Building', 
    'Lamp', 
    'Sign', 
    'Vegetation', 
    'Sky', 
    'Person', 
    'Car', 
    'Truck', 
    'Bus', 
    'Motorcycle', 
    'Bicycle', 
    'Pole'
  ]
pattale: [
      [0, 0, 0],  # background  0
      [228, 228, 179],  # Road 1
      [133, 57, 181],  # Sidewalk 2
      [177, 162, 67],  # Building 3
      [50, 178, 200],  # Lamp 4
      [199, 45, 132],  # Sign 5
      [84, 172, 66],  # Vegetation 6
      [79, 73, 179],  # Sky 7
      [166, 99, 76],  # Person 8
      [253, 121, 66],  # Car 9
      [91, 165, 137],  # Truck 10
      [152, 97, 155],  # Bus 11
      [140, 153, 105],  # Motorcycle 12
      [158, 215, 222],  # Bicycle 13
      [90, 113, 135],  # Pole 14
    ]

# Image properties
x_is_single_channel: true
train_source: "datasets/FMB/train2.txt"
eval_source: "datasets/FMB/test.txt"
is_test: false
num_train_imgs: 1220
num_eval_imgs: 280
background: 255
image_height: 600 #480 #384  #480 #384
image_width: 800 #640 #512  #640 #512
norm_mean: [0.485]
norm_std: [0.229]

# Model settings
backbone: "sigma_tiny"
pretrained_model: null
decoder: "MLPDecoder"
decoder_embed_dim: 768
rank_list:  [16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240]
spe_rank: 16
modal_num: 2
topk: 9
pre_softmax: True
modals: ['visible', 'thermal']

# Training parameters
usepretrained: True
pretrained: '/home/suguilin/MMFS/pretrained/classification/vssm1_tiny_0230s_ckpt_epoch_264.pth'
align_corners: False
optimizer: "AdamW"
lr: 0.00006 #0.0001
lr_power: 0.9
momentum: 0.9
weight_decay: 0.01
batch_size: 2 #2 #8
nepochs: 800
niters_per_epoch: 610 #153 #271 #136 #542 #136 #361 #271 #542   # 155 #271  # 542
num_workers: 16
train_scale_array: [0.5, 0.75, 1, 1.25, 1.5, 1.75]
warm_up_epoch: 10

# Loss parameters
alpha: 10     # loss_in
beta: 10      # loss_grad
gamma: 10     # loss_color
theta: 10     # loss_seg
sigma: 0.05   # loss_aux
fix_bias: true
bn_eps: 0.001
bn_momentum: 0.1

# Evaluation parameters
eval_stride_rate: 0.6667
eval_scale_array: [1]
eval_flip: false
eval_crop_size: [600, 800]

# Checkpoint settings
checkpoint_start_epoch: 50
checkpoint_step: 10
checkpoint_dir: "experiment/FMB/exp8/checkpoint"
log_dir_link: "experiment/FMB/exp8"
log_dir: "experiment/FMB/exp8"
tb_dir: "experiment/FMB/exp8/tb"

# Result settings
save_path: './experiment/FMB/exp8/result'

# Log file settings
log_file: "experiment/FMB/exp8/train_output.log"
link_log_file: "experiment/FMB/exp8/log_last.log"
val_log_file: "experiment/FMB/exp8/val_output.log"
link_val_log_file: "experiment/FMB/exp8/val_last.log"
test_log_file: "experiment/FMB/exp8/test_output.log"
