seed: 3407

# Directory settings
root_dir: "/home/suguilin/myfusion/"
abs_dir: "."
dataset_name: "MFNet"
dataset_path: "datasets/MFNet"

# Dataset settings
rgb_root_folder: "datasets/MFNet/RGB"
rgb_format: ".png"
x_root_folder: "datasets/MFNet/Modal"
x_format: ".png"
text_root_folder: "datasets/MFNet/Text_Bert" # "datasets/MFNet/Text"
text_format: ".npy" # ".txt"
guide_root_folder: "datasets/MFNet/Guide"
guide_format: ".png"
label_root_folder: "datasets/MFNet/Label"
label_format: ".png"
gt_transform: false

# Classes and labels
num_classes: 9
class_names:
  [
    "unlabeled",
    "car",
    "person",
    "bike",
    "curve",
    "car stop",
    "guardrail",
    "color cone",
    "bump",
  ]

# Image properties
x_is_single_channel: true
train_source: "datasets/MFNet/train2.txt"
eval_source: "datasets/MFNet/test.txt"
is_test: false
num_train_imgs: 1083
num_eval_imgs: 361
background: 255
image_height: 480 #384  #480 #384
image_width: 640 #512  #640 #512
norm_mean: [0.485]
norm_std: [0.229]

# Model settings
backbone: "sigma_tiny"
pretrained_model: null
decoder: "MLPDecoder"
decoder_embed_dim: 64

# Training parameters
align_corners: False
optimizer: "AdamW"
lr: 0.00006 #0.0001
lr_power: 0.9
momentum: 0.9
weight_decay: 0.01
batch_size: 2 #2 #8
nepochs: 800
niters_per_epoch: 542 #271 #136 #542 #136 #361 #271 #542   # 155 #271  # 542
num_workers: 16
train_scale_array: [0.5, 0.75, 1, 1.25, 1.5, 1.75]
warm_up_epoch: 10

# Loss parameters
alpha: 10     # loss_in
beta: 10      # loss_grad
gamma: 10     # loss_color
theta: 10     # loss_seg
sigma: 0.05   # loss_aux
fix_bias: true
bn_eps: 0.001
bn_momentum: 0.1

# Evaluation parameters
eval_stride_rate: 0.6667
eval_scale_array: [1]
eval_flip: false
eval_crop_size: [480, 640]

# Checkpoint settings
checkpoint_start_epoch: 20
checkpoint_step: 10
checkpoint_dir: "experiment/exp2/checkpoint"
log_dir_link: "experiment/exp2"
log_dir: "experiment/exp2"
tb_dir: "experiment/exp2/tb"

# Result settings
save_path: './experiment/exp2/result'

# Log file settings
log_file: "experiment/exp2/train_output.log"
link_log_file: "experiment/exp2/log_last.log"
val_log_file: "experiment/exp2/val_output.log"
link_val_log_file: "experiment/exp2/val_last.log"
test_log_file: "experiment/exp2/test_output.log"
